config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :posts do
    resources :comments
  end

  root to: "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true

end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :image, :title
  has_many :comments, dependent: :destroy


  mount_uploader :image, PhotoUploader


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :comment))
    @comment.user_id = current_user.id
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    set_meta_tags site: 'cryptowhispers.io'

    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    set_meta_tags title: @post.title,
                  site: 'Crypto Whispers',
                  reverse: true,
                  description: @post.description

  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :image, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card w-80">
  <div class="card-body p-4">

        <p class="float-left"> <%= comment.comment %> </p>


        <%# if current_user == comment.user %>
          <%#= link_to 'Delete', [comment.post, comment],
                    method: :delete, class: "btn btn-danger float-right", data: { confirm: 'Are you sure?' } %>
        <%# end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>

  <div class="form-group">
        <%= f.input :comment, input_html: { class: 'form-control text optional' }, wrapper: false, label_html: { class: 'label' }, label:false %>
  </div>

    <div class="text-center">
      <%= f.button :submit, 'Leave a reply', class: "btn btn-primary" %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Whispers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= display_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css">


  </head>

  <body>
      <nav class="site-header sticky-top py-1 bg-white">
        <div class="container d-flex flex-column flex-md-row justify-content-between">
          <a href="/">
            <%= image_tag "Logo.jpg", width: "250", height: "50"%>
          </a>

            <div>
              <% if current_user %>
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-danger btn-lg" %>
              <% else %>
                <%= link_to 'Log In', new_user_session_path, class: "btn btn-primary btn-lg" %>
                <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-lg"  %>
              <% end %>
            </div>
        </div>
      </nav>




    <%= yield %>
  </body>

  <!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.0),rgba(255,255,255,255.255)), url(<%= image_path "EthereumPurple.jpg" %>)">
  <div class="container">
      <%= image_tag "Logo.jpg", width: "400", height: "100"%>
      <p style="font-family:courier; font-size:125% "><strong>Discussing the value of solutions to crypto's biggest problems</strong></p>
  </div>
</div>




<div class="container m-5">

  <h1 class="text-center m-5" style="font-family:courier;" >Our Articles</h1>

  <div class="row d-flex">


    <% @posts.reverse.each do |post| %>

      <div class="card mx-auto m-5 rounded-bottom border-dark" style="width: 402px;">
          <a href="<%= post_url(post)  %>"  > <%= cl_image_tag(post.image.card.full_public_id, secure: true, :width => 400, :height => 300) %></a>
          <div class="card-trip-infos">
              <div class="card-body">
                <h5 class="card-title text-center "><%= link_to post.title, post, class: "text-decoration-none text-reset" %></h5>
                <p class="card-text text-center"><%= post.description.truncate_words(30).html_safe %></p>
              </div>
          </div>
       </div>
      <br>
    <% end  %>

  </div>
</div>
<br>

<div class="container">



</div>



<div class="banner" style="background-image:linear-gradient(rgba(255,255,255,255.1),rgba(0,0,0,0.0)), url(<%= image_path "EthPurple.jpg" %>);">
  <div class="colum text-center" id="contact">
  <h1 style="font-family:courier; font-size:150% "><strong>Get into contact and start contributing</strong></h1>
    <div>
      <% if current_user %>
        <p class="pt-3"style="font-family:courier;">If you have a good idea about potential, please feel free to reach out to Maxx3007 on Reddit, Github, or Slack!</p>

        <div class="icons">

              <a class="mr-3" href="https://github.com/Maxx3007" target="_blank">
                <i class="fab fa-github fa-4x" style="color:black;"></i>
                <p style="color:black;">
                  My Github
                </p>
              </a>

              <a class="ml-3" href="https://www.reddit.com/user/maxx3007" target="_blank">
                <i class="fab fa-reddit fa-4x" style="color:black;"></i>
                <p style="color:black;">
                  My Reddit
                </p>
              </a>
        </div>

      <% else %>
          <%= link_to 'Log In', new_user_session_path, class: "btn btn-primary btn-lg" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-lg"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
  <div class=" text-center">
    <%= cl_image_tag(@post.image.standard.full_public_id, secure: true, :width => 900, :height => 400) %>
  </div>


<div class="content">

<h3 class="text-center mt-5" style = "font-family:Georgia;">
  <%= @post.title %>
</h3>


<p class="text-center mt-5" style = "font-family: sans-serif;">
  <%= @post.description.html_safe %>
</p>


</div>

<p class="text-center">
  <%= link_to 'Back', root_path, class: "btn btn-primary btn-lg" %>
</p>



<div class="comments">
  <div class="container text-right">
      <h3><strong><%= @post.comments.count %></strong> Comments</h3>
      <hr>
      <%= render @post.comments %>
    <% if signed_in? %>
      <div class="comment-form">
        <hr>
          <h3 class="card-title text-center">Leave a Comment</h3>
          <%= render "comments/form" %>
      </div>
    <% else %>
      <div class="text-center m-5">
        <h3>Please Sign in to leave a comment</h3>
          <%= link_to 'Log In', new_user_session_path, class: "btn btn-primary btn-lg mt-5" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success btn-lg mt-5"  %>
      </div>
    <% end %>
  </div>
</div>